package com.kiko.kikocomponentes.navigation

sealed class Screen(val route: String) {
    object Splash : Screen("splash")
    object Main : Screen("main")
    object AlertDialog : Screen("alert_dialog")
    object AppBars : Screen("app_bars")
    object Badges : Screen("badges")
    object Buttons : Screen("buttons")
    object Cards : Screen("cards")
    object Carousel : Screen("carousel")
    object Checkbox : Screen("checkbox")
    object Chips : Screen("chips")
    object DateTime : Screen("datetime")
    object Dividers : Screen("dividers")
    object Lists : Screen("lists")
    object Loading : Screen("loading")
    object Menus : Screen("menus")
    object NavigationBar : Screen("navigation_bar")
    object Outlined : Screen("outlined")
    object RadioButton : Screen("radio")
    object Search : Screen("search")
    object Sheets : Screen("sheets")
    object Slider : Screen("slider")
    object Snackbar : Screen("snackbar")
    object Switch : Screen("switch")
    object Tabs : Screen("tabs")
    object ToolsBar : Screen("tools_bar")
    object Tooltips : Screen("tooltips")
}
